# Generated by Django 6.0.5 on 2026-05-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edge', to='route_manager.shop')),
                ('to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomming_edge', to='route_manager.shop')),
            ],
        ),
    ]
