# Generated by Django 6.0.5 on 2026-06-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0002_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
